<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style>
            body {
                font-family: DejaVu Sans, sans-serif;
                font-size: 10px;
            }
            h2#institute-name {
                width: 100%;
                display: block;
                text-align: center;
                font-size: 24px;
                margin: 20px
            }
            div#device-start-date {
                font-size: 12px;
                display: block;
                margin: 20px;
                width: 100%;
                text-align: center;
            }
            table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
                border: 1px solid #000000;
                border-collapse: collapse;
            }
            table th {
                text-align: center;
                border: 1px solid #000000;
                background-color: #FFFF00;
            }
            table td {
                vertical-align: top;
                border-right: 1px solid #000000;
                border-bottom: 1px dashed #000000;
            }
            .table-bordered {
                border: 1px solid #ddd;
            }
            div#confirmation > div {
                display: inline-block;
                text-align: center;
                float: left;
                font-weight: bold;
            }
            .col-md-3 {
                width: 30%;
            }
            .col-md-4 {
                width: 40%;
            }
        </style>
    </head>
    <body>
        <h2 id="institute-name">SỔ QUẢN LÝ TÀI SẢN VIỆN <?= $this->institute['name'] ?></h2>
        <?php if (isset($this->startDate)): ?>
            <div id="device-start-date"><i>Từ ngày <?= $this->startDate[2] ?> tháng <?= $this->startDate[1] ?> năm <?= $this->startDate[0] ?> </i></div>
        <?php endif ?>
        <table>
            <tr class="info">
                <th>TT</th>
                <th>Tên thiết bị và chỉ tiêu kỹ thuật chính</th>
                <th>Số máy</th>
                <th>N­ước SX</th>
                <th>Ngày nhập</th>
                <th>Đơn giá<br />(1000đ)</th>
                <th>Thành tiền<br />(1000đ)</th>
                <th>Tình trạng</th>
                <th>Nguồn tiền</th>
                <th>Số tài sản</th>
            </tr>
            <?php foreach ($this->data as $id => $device): ?>
            <tr>
                <td><?= ($id + 1) ?></td>
                <td><?= $device['name'] ?></td>
                <td><?= $device['sign'] ?></td>
                <td><?= $this->countries[$this->factories[$device['factory_id']]['country_id']]['name'] ?></td>
                <td>
                    <?php foreach ($device['device_increases'] as $deviceIncrease): ?>
                        <?= $deviceIncrease['increase_date'] ?><br />
                    <?php endforeach ?>
                </td>
                <td><?= $device['device_increase_cost']['sum_cost'] ?></td>
                <td><?= ($device['device_increase_cost']['sum_cost'] + $device['device_increase_cost']['sum_install_fee'] + $device['device_increase_cost']['sum_transport_fee']) ?></td>
                <td>
                    <?php foreach ($device['device_statuses'] as $deviceStatus): ?>
                        <?= $deviceStatus['name'] ?><br />
                    <?php endforeach ?>
                </td>
                <td>
                    <?php foreach ($device['device_increases'] as $deviceIncrease): ?>
                        <?= $deviceIncrease['increase_funds'] ?><br />
                    <?php endforeach ?>
                </td>
                <td>
                    <?php foreach ($device['device_details'] as $deviceDetail): ?>
                        <?= $deviceDetail['device_no'] ?><br />
                    <?php endforeach ?>
                </td>
            </tr>
            <?php endforeach ?>
        </table>
        <div class="row" id="confirmation">
            <div class="col-md-3">Phòng thiết bị</div>
            <div class="col-md-3">Viện trưởng</div>
            <div class="col-md-4">Cán bộ quản lý tài sản Viện</div>
        </div>
    </body>
</html>
