<table>
<tr>
    <td>Id</td>
    <td>Email</td>
    <td>Pass</td>
</tr>
<?php
foreach($this->data as $item)
{
    echo "<tr>";
    echo "<td align='center'>".$item['id']."</td>";
    echo "<td align='center'>".$item['email']."</td>";
    echo "<td align='center'>".$item['password']."</td>";
}
?>
</table>
<?php
       echo $this->paginationControl($this->data, 'Sliding' , 'user/pagination.phtml');
?>