<h1>Manager Attributes</h1>
<a href="<?=$this->url(array('controller'=>'attribute','action'=>'new'))?>">Create attribute</a>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Values</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->data as $item){ ?>
      <tr>
        <th scope="row"><?= $item['id'] ?></th>
        <td>
          <a href="<?=$this->url(array('controller'=>'attribute','action'=>'edit','id'=>$item['id']))?>">
            <?= $item['name'] ?>
          </a>
        </td>
        <?php $values = $this->controller->getValues($item['id']); ?>
        <td>
          <a href="<?=$this->url(array('controller'=>'attribute','action'=>'values','id'=>$item['id']))?>"><?= count($values); ?></a></td>
        <td><a href="<?=$this->url(array('controller'=>'attribute','action'=>'delete','id'=>$item['id']))?>">Delete</a></td>
      </tr>
    <?php } ?>
  </tbody>
</table>
<?php
if($this->data->count() > 1){
  echo $this->paginationControl($this->data, 'Sliding' , 'index/pagination.phtml');
}
?>