<?php
echo 'Hello '.$this->username.'!';
?>
<br/>
<a href="<?php echo APPLICATION_PATH ?>/admin/index/index">M-Admin C-Index A-Index</a><br/>
<a href="<?php echo APPLICATION_PATH ?>/admin/index/insert"> M-Admin C-Index A-Insret</a></br>
<a href="<?php echo APPLICATION_PATH ?>/admin/index/update">M-Admin C-Index A-Update</a></br>
<a href="<?php echo APPLICATION_PATH ?>/admin/index/delete">M-Admin C-Index A-Delete</a></br>