<h1>Chi tiết hóa đơn nhập</h1>
<a href="<?=$this->url(array('controller'=>'increase','action'=>'createdevice','id'=>$this->id))?>">Thêm thiết bị</a>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Tên thiết bị</th>
      <th>Ngày sản xuất</th>
      <th>Số lượng</th>
      <th>Giá trị</th>
      <th>Khấu hao</th>
      <th>Bảo hành</th>
      <th>Phí lắp đặt</th>
      <th>Phí vận chuyển</th>
      <th>Thành tiền</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php $total = 0; ?>
    <?php foreach($this->data as $index => $item){ ?>
      <?php $expenses = $item['cost'] * $item['quantity'] + $item['install_fee'] + $item['transport_fee'] ?>
      <?php $total += $expenses ?>
      <tr>
        <th scope="row"><?= $index+1 ?></th>
        <td>
          <a href="<?=$this->url(array('controller'=>'increase','action'=>'editdevice','id'=>$item['id']))?>">
            <?= $this->controller->getDevice($item['device_id'])['name'] ?>
          </a>
        </td>
        <td><?= $item['production_date'] ?></td>
        <td><?= $item['quantity'] ?></td>
        <td><?= $item['cost'] ?></td>
        <td><?= $item['amortized'] ?> tháng</td>
        <td><?= $item['guarantee'] ?> tháng</td>
        <td><?= $item['install_fee'] ?></td>
        <td><?= $item['transport_fee'] ?></td>
        <td><?= $expenses ?></td>
        <td><a href="<?=$this->url(array('controller'=>'increase','action'=>'deletedevice','id'=>$item['id']))?>">Xóa thiết bị</a></td>
      </tr>
    <?php } ?>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Tổng cộng:</td>
      <td><?= $total ?></td>
      <td></td>
    </tr>
  </tbody>
</table>
<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'increase','action'=>'index'),
null, true)?>" class="btn btn-primary">Quay lại</a>
<?php
if($this->data->count() > 1){
  echo $this->paginationControl($this->data, 'Sliding' , 'index/pagination.phtml');
}
?>