<h1>Manager increases</h1>
<a href="<?=$this->url(array('controller'=>'increase','action'=>'new'))?>">Add new</a>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Invoice</th>
      <th>Date</th>
      <th>Provider</th>
      <th>Funds</th>
      <th>Details</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->data as $item){ ?>
      <tr>
        <th scope="row"><?= $item['id'] ?></th>
        <td>
          <a href="<?=$this->url(array('controller'=>'increase','action'=>'edit','id'=>$item['id']))?>">
            <?= $item['invoice_no'] ?>
          </a>
        </td>
        <td><?= $item['increase_date'] ?></td>
        <td>
          <a href="<?=$this->url(array('controller'=>'provider','action'=>'show','id'=>$item['provider_id']))?>" target='_blank'><?= $this->controller->getProvider($item['provider_id'])['name'] ?></a></td>
        <td><?= $item['funds'] ?></td>
        <td>
          <a href="<?=$this->url(array('controller'=>'increase','action'=>'devices','id'=>$item['id']))?>">detail</a>
        </td>
        <td><a href="<?=$this->url(array('controller'=>'increase','action'=>'delete','id'=>$item['id']))?>">Delete</a></td>   
      </tr>
    <?php } ?>
  </tbody>
</table>
<?php
if($this->data->count() > 1){
  echo $this->paginationControl($this->data, 'Sliding' , 'index/pagination.phtml');
}
?>