<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <a href="<?=$this->url(array('controller'=>'index',
                    'action'=>'index'), null, true)?>" id="logo">BKDMS</a>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <?php if (empty($this->user)): ?>
                    <li><a href="<?=$this->url(array('controller'=>'index',
                    'action'=>'login'), null, true)?>">Đăng nhập</a></li>
                <?php else: ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Báo cáo<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'report',
                                'action'=>'institute-device'), null, true)?>">Kiểm kê tài sản viện</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Tìm kiếm<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'search',
                                'action'=>'information'), null, true)?>">Thông tin thiết bị</a></li>
                            <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'search',
                                'action'=>'address'), null, true)?>">Địa điểm</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Thông tin thiết bị<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <?php if($this->user->level == 1): ?>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'device',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Danh mục thiết bị</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'attribute',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Thuộc tính</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'factory',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Nhà sản xuất</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'provider',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Nhà phân phối</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'type',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Loại thiết bị</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'status',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Trạng thái</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'country',
                                'module'=>'admin', 'action'=>'index'), null, true)?>">Nước sản xuất</a></li>
                            <?php else: ?>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Xử lý thiết bị<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <?php if($this->user->level == 1): ?>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'increase',
                                'action'=>'index'), null, true)?>">Nhập mới</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'repair',
                                'action'=>'index'), null, true)?>">Sửa chữa</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'disposal',
                                'action'=>'index'), null, true)?>">Thanh lý</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'borrow',
                                'action'=>'index'), null, true)?>">Sử dụng</a></li>
                                <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'transfer',
                                'action'=>'index'), null, true)?>">Thuyên chuyển</a></li>
                            <?php else: ?>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <?php if($this->user->level == 1): ?>
                        <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'user',
                        'action'=>'index'), null, true)?>">Người dùng</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Đơn vị<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'room',
                                    'module'=>'admin', 'action'=>'index'), null, true)?>">Phòng</a></li>
                                    <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'building',
                                    'module'=>'admin', 'action'=>'index'), null, true)?>">Toà nhà</a></li>
                                    <li><a href="<?=$this->url(array('module'=>'admin', 'controller'=>'institute',
                                    'module'=>'admin', 'action'=>'index'), null, true)?>">Khoa viện</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Hệ thống<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                    <li><a href="">Phân quyền</a></li>
                                    <li><a href="">Sao lưu</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?=$this->url(array('controller'=>'index',
                                    'action'=>'logout'), null, true)?>">Đăng xuất</a></li>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Tài khoản<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url(array('controller'=>'user',
                                    'action'=>'show'), null, true)?>">Hồ sơ</a></li>
                                    <li><a href="<?=$this->url(array('controller'=>'user',
                                    'action'=>'edit'), null, true)?>">Cài đặt</a></li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?=$this->url(array('controller'=>'index',
                                    'action'=>'logout'), null, true)?>">Đăng xuất</a>
                                </li>
                            </ul>
                        </li>
                    <?php endif; ?>
                <?php endif; ?>
            </ul>
        </nav>
    </div>
</header>
