<h1>Manager Countries</h1>
<a href="<?=$this->url(array('controller'=>'country','action'=>'new'))?>">Create country</a>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Code</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->data as $item){ ?>
      <tr>
        <th scope="row"><?= $item['id'] ?></th>
        <td>
          <a href="<?=$this->url(array('controller'=>'country','action'=>'edit','id'=>$item['id']))?>">
            <?= $item['name'] ?>
          </a>
        </td>
        <td><?= $item['code'] ?></td>
        <td><a href="<?=$this->url(array('controller'=>'country','action'=>'delete','id'=>$item['id']))?>">Delete</a></td>
      </tr>
    <?php } ?>
  </tbody>
</table>
<?php
if($this->data->count() > 1){
  echo $this->paginationControl($this->data, 'Sliding' , 'index/pagination.phtml');
}
?>