<h1>Transfer's Detail</h1>
<a href="<?=$this->url(array('controller'=>'transfer','action'=>'createdevice','id'=>$this->id))?>">Add device</a>
<table class="table">
  <thead>
    <tr>
      <th>STT</th>
      <th>Device name</th>
      <th>Country</th>
      <th>Increase date</th>
      <th>Increase cost</th>
      <th>Status</th>
      <th>Funds</th>
      <th>Old sign</th>
      <th>New sign</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->data as $key=>$item){ ?>
      <tr>
        <td><?= $key+1 ?></td>
        <td>
          <a href="<?=$this->url(array('controller'=>'device','action'=>'show','id'=>$this->controller->getDevice($this->controller->getDeviceDetail($item['device_id'])['device_id'])['id']))?>">
            <?= $this->controller->getDevice($this->controller->getDeviceDetail($item['device_id'])['device_id'])['name'] ?>
          </a>
        </td>
        <td><?= $this->controller->getCountry($item['device_id'])['name'] ?></td>
        <td><?= $this->controller->getIncrease($this->controller->getDeviceDetail($item['device_id'])['increase_id'])['increase_date'] ?></td>
        <td><?= $this->controller->getIncreaseCost($item['device_id'])['cost'] ?></td>
        <td><?= $this->controller->getStatus($item['device_id'])['name'] ?></td>
        <td><?= $this->controller->getIncrease($this->controller->getDeviceDetail($item['device_id'])['increase_id'])['funds'] ?></td>
        <td><?= $this->controller->getDeviceOld($item['device_id'], $item['transfer_id']) ?></td>
        <td><?= $this->controller->getDeviceDetail($item['device_id'])['device_no'] ?></td>
        <td><a href="<?=$this->url(array('controller'=>'transfer','action'=>'deletedevice','id'=>$item['id']))?>">Delete</a></td>
      </tr>
    <?php } ?>
  </tbody>
</table>
<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'transfer','action'=>'index'),
null, true)?>" class="btn btn-primary">Back</a>
<?php
if($this->data->count() > 1){
  echo $this->paginationControl($this->data, 'Sliding' , 'index/pagination.phtml');
}
?>