<h1>Manager disposals</h1>
<a href="<?=$this->url(array('controller'=>'disposal','action'=>'new'))?>">Add new</a>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Provider</th>
      <th>Description</th>
      <th>Details</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->data as $item){ ?>
      <tr>
        <th scope="row"><?= $item['id'] ?></th>
        <td>
          <a href="<?=$this->url(array('controller'=>'disposal','action'=>'edit','id'=>$item['id']))?>">
            <?= $item['disposal_date'] ?>
          </a>
        </td>
        <td>
          <a href="<?=$this->url(array('controller'=>'provider','action'=>'show','id'=>$item['provider_id']))?>" target='_blank'><?= $this->controller->getProvider($item['provider_id'])['name'] ?></a></td>
        <td><?= $item['description'] ?></td>
        <td>
          <a href="<?=$this->url(array('controller'=>'disposal','action'=>'devices','id'=>$item['id']))?>">detail</a>
        </td>
        <td><a href="<?=$this->url(array('controller'=>'disposal','action'=>'delete','id'=>$item['id']))?>">Delete</a></td>
      </tr>
    <?php } ?>
  </tbody>
</table>
<input type="text" id="datepicker">
<?php
if($this->data->count() > 1){
  echo $this->paginationControl($this->data, 'Sliding' , 'index/pagination.phtml');
}
?>
<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
  </script>