<h1>Provider's infomation</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <dt><label>Name:</label></dt>
    <?= $this->provider['name'] ?>
    <dt><label>Description:</label></dt>
    <?= $this->provider['description'] ?>
    <dt><label>Phone:</label></dt>
    <?= $this->provider['phone'] ?>
    <dt><label>Email:</label></dt>
    <?= $this->provider['email'] ?>
    <dt><label>Address:</label></dt>
    <?= $this->provider['address'] ?>
  </div>
</div>